#!/bin/sh

# this will explain the layout of the processors for the j1900 quantum & similar units
# cpu(eth0) is know to the system as eth1 hence (1)
# cpu0= (1) | cpu1= (2) | cpu2= (4) | cpu3= (8)

# each line will pin the system irq's
awk '/eth0/ { gsub(/:/,""); print $1}' /proc/interrupts | while read i; do echo "e" > /proc/irq/$i/smp_affinity;done
awk '/eth1/ { gsub(/:/,""); print $1}' /proc/interrupts | while read i; do echo "e" > /proc/irq/$i/smp_affinity;done
awk '/eth2/ { gsub(/:/,""); print $1}' /proc/interrupts | while read i; do echo "e" > /proc/irq/$i/smp_affinity;done
awk '/eth3/ { gsub(/:/,""); print $1}' /proc/interrupts | while read i; do echo "e" > /proc/irq/$i/smp_affinity;done

awk '/i915/ { gsub(/:/,""); print $1}' /proc/interrupts | while read i; do echo "e" > /proc/irq/$i/smp_affinity;done
awk '/ahci/ { gsub(/:/,""); print $1}' /proc/interrupts | while read i; do echo "e" > /proc/irq/$i/smp_affinity;done

# (the default for openwrt v19 is powersaving, which works just fine). change the scaling governor to performance instead of powersaving
#find /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor -exec sh -c 'echo performance > {}' \;

sleep 15

# configure ethtool RSS to spread among the cores
for NICS in eth0 eth1 eth2 eth3; do
        ethtool -X $NICS equal 2
done

# the default cpu is 0, which we want to exclude so as to utilize the other processors. this sets each receive and transmit packet steering element rps_cpus to  (2+4+8), or e (the hexadecimal value for 14).
find /sys/class/net/*/queues/rx-[01]/rps_cpus -exec sh -c '[ -w {} ] && echo "e" > {} 2>/dev/null' \;
