#!/bin/sh /etc/rc.common

START=100

start() {

logger -t tweak-cpu "Starting Tweak Cpu Core"
	
IFACE=$(ls /sys/class/net)
	
for i in ${IFACE}; do
	ethtool -K $i gro on 2>/dev/null
	if [[ -e /sys/class/net/$i/queues/rx-0/rps_cpus ]]; then
		if [[ $i = "wwan0" ]]; then
			echo f > /sys/class/net/$i/queues/rx-0/rps_cpus
		else
			echo f > /sys/class/net/$i/queues/rx-0/rps_cpus
		fi
	fi
done

cat > /tmp/resolv.conf.auto <<-DNS001
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
DNS001

cat > /etc/resolv.conf <<-DNS002
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
DNS002

cat > /tmp/resolv.conf <<-DNS003
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
DNS003

}

stop() {

logger -t tweak cpu "Stopping Tweak Cpu Core"

IFACE=$(ls /sys/class/net)
	
for i in ${IFACE}; do
	ethtool -K $i gro on 2>/dev/null
	if [[ -e /sys/class/net/$i/queues/rx-0/rps_cpus ]]; then
		if [[ $i = "wwan0" ]]; then
			echo f > /sys/class/net/$i/queues/rx-0/rps_cpus
		else
			echo f > /sys/class/net/$i/queues/rx-0/rps_cpus
		fi
	fi
done

cat > /tmp/resolv.conf.auto <<-DNS001
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
DNS001

cat > /etc/resolv.conf <<-DNS002
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
DNS002

cat > /tmp/resolv.conf <<-DNS003
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
DNS003

}
