#!/bin/sh /etc/rc.common

START=99

start() {

logger -t tweak-cpu "Starting Tweak Cpu Core"
	
echo 2048 > /proc/sys/dev/nss/n2hcfg/n2h_queue_limit_core0
echo 2048 > /proc/sys/dev/nss/n2hcfg/n2h_queue_limit_core1

}

stop() {

logger -t tweak cpu "Stopping Tweak Cpu Core"

echo 2048 > /proc/sys/dev/nss/n2hcfg/n2h_queue_limit_core0
echo 2048 > /proc/sys/dev/nss/n2hcfg/n2h_queue_limit_core1

}
