#!/bin/sh /etc/rc.common

START=99

start() {

logger -t firewall-custom "Starting custom firewall rules"

nft add rule inet fw4 mangle_forward oifname wwan0_1 ip ttl set 64
nft add rule inet fw4 mangle_forward oifname wwan0_1 ip6 hoplimit set 64

nft add rule inet fw4 mangle_prerouting oifname wwan0_1 ip ttl set 64
nft add rule inet fw4 mangle_prerouting oifname wwan0_1 ip6 hoplimit set 64

nft add rule inet fw4 mangle_postrouting oifname wwan0_1 ip ttl set 64
nft add rule inet fw4 mangle_postrouting oifname wwan0_1 ip6 hoplimit set 64


nft insert rule inet fw4 mangle_prerouting oifname wwan0_1 ip ttl set 64
nft insert rule inet fw4 mangle_prerouting oifname wwan0_1 ip6 hoplimit set 64

nft insert rule inet fw4 mangle_postrouting oifname wwan0_1 ip ttl set 64
nft insert rule inet fw4 mangle_postrouting oifname wwan0_1 ip6 hoplimit set 64

#
nft add rule inet fw4 mangle_forward oifname wwan0 ip ttl set 64
nft add rule inet fw4 mangle_forward oifname wwan0 ip6 hoplimit set 64

nft add rule inet fw4 mangle_prerouting oifname wwan0 ip ttl set 64
nft add rule inet fw4 mangle_prerouting oifname wwan0 ip6 hoplimit set 64

nft add rule inet fw4 mangle_postrouting oifname wwan0 ip ttl set 64
nft add rule inet fw4 mangle_postrouting oifname wwan0 ip6 hoplimit set 64


nft insert rule inet fw4 mangle_prerouting oifname wwan0 ip ttl set 64
nft insert rule inet fw4 mangle_prerouting oifname wwan0 ip6 hoplimit set 64

nft insert rule inet fw4 mangle_postrouting oifname wwan0 ip ttl set 64
nft insert rule inet fw4 mangle_postrouting oifname wwan0 ip6 hoplimit set 64
}

stop() {

logger -t firewall-custom "Stopping custom firewall rules"

nft add rule inet fw4 mangle_forward oifname wwan0_1 ip ttl set 64
nft add rule inet fw4 mangle_forward oifname wwan0_1 ip6 hoplimit set 64

nft add rule inet fw4 mangle_prerouting oifname wwan0_1 ip ttl set 64
nft add rule inet fw4 mangle_prerouting oifname wwan0_1 ip6 hoplimit set 64

nft add rule inet fw4 mangle_postrouting oifname wwan0_1 ip ttl set 64
nft add rule inet fw4 mangle_postrouting oifname wwan0_1 ip6 hoplimit set 64


nft insert rule inet fw4 mangle_prerouting oifname wwan0_1 ip ttl set 64
nft insert rule inet fw4 mangle_prerouting oifname wwan0_1 ip6 hoplimit set 64

nft insert rule inet fw4 mangle_postrouting oifname wwan0_1 ip ttl set 64
nft insert rule inet fw4 mangle_postrouting oifname wwan0_1 ip6 hoplimit set 64

#
nft add rule inet fw4 mangle_forward oifname wwan0 ip ttl set 64
nft add rule inet fw4 mangle_forward oifname wwan0 ip6 hoplimit set 64

nft add rule inet fw4 mangle_prerouting oifname wwan0 ip ttl set 64
nft add rule inet fw4 mangle_prerouting oifname wwan0 ip6 hoplimit set 64

nft add rule inet fw4 mangle_postrouting oifname wwan0 ip ttl set 64
nft add rule inet fw4 mangle_postrouting oifname wwan0 ip6 hoplimit set 64


nft insert rule inet fw4 mangle_prerouting oifname wwan0 ip ttl set 64
nft insert rule inet fw4 mangle_prerouting oifname wwan0 ip6 hoplimit set 64

nft insert rule inet fw4 mangle_postrouting oifname wwan0 ip ttl set 64
nft insert rule inet fw4 mangle_postrouting oifname wwan0 ip6 hoplimit set 64

}
